# Generated by Django 3.2.12 on 2024-05-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enregistrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('file', models.BinaryField()),
                ('file_type', models.CharField(max_length=10)),
            ],
        ),
    ]
