# Generated by Django 3.2.12 on 2024-05-02 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enregistrement',
            name='file',
        ),
        migrations.RemoveField(
            model_name='enregistrement',
            name='file_type',
        ),
        migrations.AddField(
            model_name='enregistrement',
            name='cours',
            field=models.FileField(default='', upload_to='fichiers/'),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
