# Generated by Django 3.2.12 on 2024-05-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0002_auto_20240502_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='cours',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
