# Generated by Django 3.2.12 on 2024-05-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0004_alter_enregistrement_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='enregistrement',
            name='prof',
            field=models.CharField(default='anonyme', max_length=50),
        ),
    ]
